In [5]:
import pandas as pd

df = pd.read_csv('customer_shopping_behavior.csv')

df.describe(include = 'all')
#df.info() shows all the information
#df.head() shows the forst 5 rowws
#df.tail() shows the last 5 rows
df.describe(include='all')
#THE ABOve one gives statistical values for all numerical and non numerical values

#df.describe() tells for each column count, mean, std, min, max, 25%, 50%, 75% (i.e all the statistical values).

df.isnull().sum()
#this tells us about the values in each column which are 0

#to fill the 0 values it is better to use median rather than mean as mean can be affected by outliers more
#we will find median review rating witihn each caetgory so that it gets the rating of its own category like for shoes
#the review will only be used of shoes
#transform() means:"Perform an operation on each group but return a result with the same number of rows as the original DataFrame."
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))
#lets check for anyother null values left by using df.isnull().sum()
df['Review Rating'].tail()

3895    4.2
3896    4.5
3897    2.9
3898    3.8
3899    3.1
Name: Review Rating, dtype: float64

In [6]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
#These 2 process converted uppercase to snakecase
#snake casing: lower case with underscore

In [7]:
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [8]:
labels=['young adults', 'adult', 'middle-aged', 'senior',]
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [9]:
df[['age', 'age_group']].head(10)

   age     age_group
0   55   middle-aged
1   19  young adults
2   50   middle-aged
3   21  young adults
4   45   middle-aged
5   46   middle-aged
6   63        senior
7   27  young adults
8   26  young adults
9   57   middle-aged

In [10]:
#frequency mapping
#In pandas, frequency mapping refers to the process of substituting every value in a S eries or DataFrame column with a corresponding numeric frequency
#here creating column purchase_frequency_days
frequency_mapping={
     'Fortnightly':4,
     'Weekly':7,
     'Monthly':30,
     'Quarterly':90,
     'Bi-weekly':14,
     'Annually':365
 }
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [11]:
df[['purchase_frequency_days', 'frequency_of_purchases']]

      purchase_frequency_days frequency_of_purchases
0                         4.0            Fortnightly
1                         4.0            Fortnightly
2                         7.0                 Weekly
3                         7.0                 Weekly
4                       365.0               Annually
...                       ...                    ...
3895                      7.0                 Weekly
3896                      NaN              Bi-Weekly
3897                     90.0              Quarterly
3898                      7.0                 Weekly
3899                     90.0              Quarterly

[3900 rows x 2 columns]

In [13]:
df[['discount_applied','promo_code_used']].head(11)

   discount_applied promo_code_used
0               Yes             Yes
1               Yes             Yes
2               Yes             Yes
3               Yes             Yes
4               Yes             Yes
5               Yes             Yes
6               Yes             Yes
7               Yes             Yes
8               Yes             Yes
9               Yes             Yes
10              Yes             Yes

In [14]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [31]:
#axis=1 is for columns
#axis=2 for rows
df = df.drop('promo_code_used', axis = 1)

KeyError: "['promo_code_used'] not found in axis"

In [17]:
df.head(6)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,middle-aged,4.0
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,young adults,4.0
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,middle-aged,7.0
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,young adults,7.0
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,middle-aged,365.0
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,Yes,14,Venmo,Weekly,middle-aged,7.0

In [24]:
pip install mysql-connector-python sqlalchemy pymysql pandas

Requirement already satisfied: mysql-connector-python in C:\Users\RAJEEV\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (9.7.0)
Requirement already satisfied: sqlalchemy in C:\Users\RAJEEV\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.0.51)
Requirement already satisfied: pymysql in C:\Users\RAJEEV\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.2.0)
Requirement already satisfied: pandas in C:\Users\RAJEEV\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.3)
Requirement already satisfied: greenlet>=1 in C:\Users\RAJEEV\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy) (3.5.3)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\RAJEEV\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\RAJEEV\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\RAJEEV\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\RAJEEV\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\RAJEEV\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [25]:
from sqlalchemy import create_engine
import pandas as pd

# format: mysql+pymysql://username:password@host:port/database_name
engine = create_engine("mysql+pymysql://root:Arch!e2515@localhost:3306/customer")

# test connection
with engine.connect() as conn:
    print("Connected successfully!")

Connected successfully!

In [27]:
df.to_sql(
    name="customer_shopping_behavior.csv",
    con=engine,
    if_exists="replace",   # options: 'fail', 'replace', 'append'
    index=False
)

3900

3900